[package]
name = "rktae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }

